baseurl = "https://www.momoh.sh/"
languageCode = "en-gb"
theme = ["hugo-jf2", "hello-friend-ng"]
title = "Shaquille's Weblog"
paginate = 10

pygmentsCodefences = false
pygmentsUseClasses = false

rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

googleAnalytics = "UA-137823237-1"
disqusShortname = "momohsh"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "media"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = true
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  FirstName = "Shaquille"
  LastName = "Momoh"
  Location = "London, UK"
  Email = "aq@mommoh.sh"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "categories"
  series = "series"

[outputs]
  # <domain>/jf2feed.json
  home = ["HTML", "RSS", "JF2Feed"]     # default = ["HTML", "RSS"]
  # <domain>/posts/jf2feed.json
  section = ["HTML", "RSS", "JF2Feed"]  # default = ["HTML", "RSS"]
  # <domain>/tags/mytag/jf2feed.json, <domain>/categories/mycat/jf2feed.json
  taxonomy = ["HTML", "RSS", "JF2Feed"] # default = ["HTML", "RSS"]
  # <domain>/posts/mypost/jf2post.json
  page = ["HTML", "JF2Post"]    

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "dark"

  # Metadata mostly used in document's head
  description = "Shaquille's Weblog"
  keywords = "weblog, blog, science, machine learning, artificial intelligence, diversity, development, programming"
  images = [""]

  gitUrl = "https://github.com/shaq/momohsh/commit/"

  homeTitle = "Shaquille Momoh"
  homeSubtitle = "(said: sha·kiel mo·mo)"
  copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  menuMore = "more"
  writtenBy = "scribbled by"
  readMore = "read some more"
  readOtherPosts = "other posts"
  newerPosts = "newer posts"
  olderPosts = "older posts"
  minuteReadingTime = "min read"
  RSSSections = ["posts", "microposts", "photos"]

  [params.logo]
    logoText = "# cd ~/"
    logoHomeLink = "/"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/shaqzle/"

  [[params.social]]
    name = "instagram"
    url  = "https://instagram.com/shaqzle/"

  [[params.social]]
    name = "email"
    url  = "mailto:aq@momoh.sh"

  [[params.social]]
    name = "github"
    url  = "https://github.com/shaq/"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/shaquillemomoh/"

[menu]    
  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about"
  [[menu.main]]
    identifier = "microposts"
    name = "microblog"
    url = "/microposts/"
  [[menu.main]]
    identifier = "posts"
    name = "blog"
    url = "/posts/"
  [[menu.main]]
    identifier = "photos"
    name = "photoblog"
    url = "/photos/"
  [[menu.main]]
    identifier = "resume.pdf"
    # name = "resume"
    url = "/resume.pdf"
  [[menu.main]]
    identifier = "media"
    url = "/media/"
